#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESSAU.ControlGestion.EmisorCorreo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DESSAU_ControlGestion")]
	public partial class DESSAUControlGestionCorreoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTipoEstadoNotificacion(TipoEstadoNotificacion instance);
    partial void UpdateTipoEstadoNotificacion(TipoEstadoNotificacion instance);
    partial void DeleteTipoEstadoNotificacion(TipoEstadoNotificacion instance);
    partial void InsertNotificacion(Notificacion instance);
    partial void UpdateNotificacion(Notificacion instance);
    partial void DeleteNotificacion(Notificacion instance);
    partial void InsertTipoNotificacion(TipoNotificacion instance);
    partial void UpdateTipoNotificacion(TipoNotificacion instance);
    partial void DeleteTipoNotificacion(TipoNotificacion instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertCorreo(Correo instance);
    partial void UpdateCorreo(Correo instance);
    partial void DeleteCorreo(Correo instance);
    #endregion
		
		public DESSAUControlGestionCorreoDataContext() : 
				base(global::DESSAU.ControlGestion.EmisorCorreo.Properties.Settings.Default.DESSAU_ControlGestionConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DESSAUControlGestionCorreoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DESSAUControlGestionCorreoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DESSAUControlGestionCorreoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DESSAUControlGestionCorreoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TipoEstadoNotificacion> TipoEstadoNotificacions
		{
			get
			{
				return this.GetTable<TipoEstadoNotificacion>();
			}
		}
		
		public System.Data.Linq.Table<Notificacion> Notificacions
		{
			get
			{
				return this.GetTable<Notificacion>();
			}
		}
		
		public System.Data.Linq.Table<TipoNotificacion> TipoNotificacions
		{
			get
			{
				return this.GetTable<TipoNotificacion>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Correo> Correos
		{
			get
			{
				return this.GetTable<Correo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoEstadoNotificacion")]
	public partial class TipoEstadoNotificacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdTipoEstadoNotificacion;
		
		private string _Nombre;
		
		private EntitySet<Notificacion> _Notificacions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTipoEstadoNotificacionChanging(int value);
    partial void OnIdTipoEstadoNotificacionChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public TipoEstadoNotificacion()
		{
			this._Notificacions = new EntitySet<Notificacion>(new Action<Notificacion>(this.attach_Notificacions), new Action<Notificacion>(this.detach_Notificacions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoEstadoNotificacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdTipoEstadoNotificacion
		{
			get
			{
				return this._IdTipoEstadoNotificacion;
			}
			set
			{
				if ((this._IdTipoEstadoNotificacion != value))
				{
					this.OnIdTipoEstadoNotificacionChanging(value);
					this.SendPropertyChanging();
					this._IdTipoEstadoNotificacion = value;
					this.SendPropertyChanged("IdTipoEstadoNotificacion");
					this.OnIdTipoEstadoNotificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoEstadoNotificacion_Notificacion", Storage="_Notificacions", ThisKey="IdTipoEstadoNotificacion", OtherKey="IdTipoEstadoNotificacion")]
		public EntitySet<Notificacion> Notificacions
		{
			get
			{
				return this._Notificacions;
			}
			set
			{
				this._Notificacions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Notificacions(Notificacion entity)
		{
			this.SendPropertyChanging();
			entity.TipoEstadoNotificacion = this;
		}
		
		private void detach_Notificacions(Notificacion entity)
		{
			this.SendPropertyChanging();
			entity.TipoEstadoNotificacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Notificacion")]
	public partial class Notificacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdNotificacion;
		
		private int _IdTipoNotificacion;
		
		private int _IdTipoEstadoNotificacion;
		
		private int _IdUsuario;
		
		private System.DateTime _FechaCreacion;
		
		private System.Nullable<System.DateTime> _FechaPostpuesto;
		
		private string _Mensaje;
		
		private string _Accion;
		
		private EntityRef<TipoEstadoNotificacion> _TipoEstadoNotificacion;
		
		private EntityRef<TipoNotificacion> _TipoNotificacion;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdNotificacionChanging(int value);
    partial void OnIdNotificacionChanged();
    partial void OnIdTipoNotificacionChanging(int value);
    partial void OnIdTipoNotificacionChanged();
    partial void OnIdTipoEstadoNotificacionChanging(int value);
    partial void OnIdTipoEstadoNotificacionChanged();
    partial void OnIdUsuarioChanging(int value);
    partial void OnIdUsuarioChanged();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    partial void OnFechaPostpuestoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaPostpuestoChanged();
    partial void OnMensajeChanging(string value);
    partial void OnMensajeChanged();
    partial void OnAccionChanging(string value);
    partial void OnAccionChanged();
    #endregion
		
		public Notificacion()
		{
			this._TipoEstadoNotificacion = default(EntityRef<TipoEstadoNotificacion>);
			this._TipoNotificacion = default(EntityRef<TipoNotificacion>);
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNotificacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdNotificacion
		{
			get
			{
				return this._IdNotificacion;
			}
			set
			{
				if ((this._IdNotificacion != value))
				{
					this.OnIdNotificacionChanging(value);
					this.SendPropertyChanging();
					this._IdNotificacion = value;
					this.SendPropertyChanged("IdNotificacion");
					this.OnIdNotificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoNotificacion", DbType="Int NOT NULL")]
		public int IdTipoNotificacion
		{
			get
			{
				return this._IdTipoNotificacion;
			}
			set
			{
				if ((this._IdTipoNotificacion != value))
				{
					if (this._TipoNotificacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTipoNotificacionChanging(value);
					this.SendPropertyChanging();
					this._IdTipoNotificacion = value;
					this.SendPropertyChanged("IdTipoNotificacion");
					this.OnIdTipoNotificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoEstadoNotificacion", DbType="Int NOT NULL")]
		public int IdTipoEstadoNotificacion
		{
			get
			{
				return this._IdTipoEstadoNotificacion;
			}
			set
			{
				if ((this._IdTipoEstadoNotificacion != value))
				{
					if (this._TipoEstadoNotificacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTipoEstadoNotificacionChanging(value);
					this.SendPropertyChanging();
					this._IdTipoEstadoNotificacion = value;
					this.SendPropertyChanged("IdTipoEstadoNotificacion");
					this.OnIdTipoEstadoNotificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL")]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaPostpuesto", DbType="Date")]
		public System.Nullable<System.DateTime> FechaPostpuesto
		{
			get
			{
				return this._FechaPostpuesto;
			}
			set
			{
				if ((this._FechaPostpuesto != value))
				{
					this.OnFechaPostpuestoChanging(value);
					this.SendPropertyChanging();
					this._FechaPostpuesto = value;
					this.SendPropertyChanged("FechaPostpuesto");
					this.OnFechaPostpuestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this.OnMensajeChanging(value);
					this.SendPropertyChanging();
					this._Mensaje = value;
					this.SendPropertyChanged("Mensaje");
					this.OnMensajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Accion", DbType="NVarChar(255)")]
		public string Accion
		{
			get
			{
				return this._Accion;
			}
			set
			{
				if ((this._Accion != value))
				{
					this.OnAccionChanging(value);
					this.SendPropertyChanging();
					this._Accion = value;
					this.SendPropertyChanged("Accion");
					this.OnAccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoEstadoNotificacion_Notificacion", Storage="_TipoEstadoNotificacion", ThisKey="IdTipoEstadoNotificacion", OtherKey="IdTipoEstadoNotificacion", IsForeignKey=true)]
		public TipoEstadoNotificacion TipoEstadoNotificacion
		{
			get
			{
				return this._TipoEstadoNotificacion.Entity;
			}
			set
			{
				TipoEstadoNotificacion previousValue = this._TipoEstadoNotificacion.Entity;
				if (((previousValue != value) 
							|| (this._TipoEstadoNotificacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoEstadoNotificacion.Entity = null;
						previousValue.Notificacions.Remove(this);
					}
					this._TipoEstadoNotificacion.Entity = value;
					if ((value != null))
					{
						value.Notificacions.Add(this);
						this._IdTipoEstadoNotificacion = value.IdTipoEstadoNotificacion;
					}
					else
					{
						this._IdTipoEstadoNotificacion = default(int);
					}
					this.SendPropertyChanged("TipoEstadoNotificacion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoNotificacion_Notificacion", Storage="_TipoNotificacion", ThisKey="IdTipoNotificacion", OtherKey="IdTipoNotificacion", IsForeignKey=true)]
		public TipoNotificacion TipoNotificacion
		{
			get
			{
				return this._TipoNotificacion.Entity;
			}
			set
			{
				TipoNotificacion previousValue = this._TipoNotificacion.Entity;
				if (((previousValue != value) 
							|| (this._TipoNotificacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoNotificacion.Entity = null;
						previousValue.Notificacions.Remove(this);
					}
					this._TipoNotificacion.Entity = value;
					if ((value != null))
					{
						value.Notificacions.Add(this);
						this._IdTipoNotificacion = value.IdTipoNotificacion;
					}
					else
					{
						this._IdTipoNotificacion = default(int);
					}
					this.SendPropertyChanged("TipoNotificacion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Notificacion", Storage="_Usuario", ThisKey="IdUsuario", OtherKey="IdUsuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Notificacions.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Notificacions.Add(this);
						this._IdUsuario = value.IdUsuario;
					}
					else
					{
						this._IdUsuario = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoNotificacion")]
	public partial class TipoNotificacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdTipoNotificacion;
		
		private string _Nombre;
		
		private EntitySet<Notificacion> _Notificacions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTipoNotificacionChanging(int value);
    partial void OnIdTipoNotificacionChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public TipoNotificacion()
		{
			this._Notificacions = new EntitySet<Notificacion>(new Action<Notificacion>(this.attach_Notificacions), new Action<Notificacion>(this.detach_Notificacions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoNotificacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdTipoNotificacion
		{
			get
			{
				return this._IdTipoNotificacion;
			}
			set
			{
				if ((this._IdTipoNotificacion != value))
				{
					this.OnIdTipoNotificacionChanging(value);
					this.SendPropertyChanging();
					this._IdTipoNotificacion = value;
					this.SendPropertyChanged("IdTipoNotificacion");
					this.OnIdTipoNotificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoNotificacion_Notificacion", Storage="_Notificacions", ThisKey="IdTipoNotificacion", OtherKey="IdTipoNotificacion")]
		public EntitySet<Notificacion> Notificacions
		{
			get
			{
				return this._Notificacions;
			}
			set
			{
				this._Notificacions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Notificacions(Notificacion entity)
		{
			this.SendPropertyChanging();
			entity.TipoNotificacion = this;
		}
		
		private void detach_Notificacions(Notificacion entity)
		{
			this.SendPropertyChanging();
			entity.TipoNotificacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdUsuario;
		
		private int _IdTipoUsuario;
		
		private string _Nombre;
		
		private string _ApellidoPaterno;
		
		private string _Correo;
		
		private string _Contacto;
		
		private EntitySet<Notificacion> _Notificacions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdUsuarioChanging(int value);
    partial void OnIdUsuarioChanged();
    partial void OnIdTipoUsuarioChanging(int value);
    partial void OnIdTipoUsuarioChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoPaternoChanging(string value);
    partial void OnApellidoPaternoChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnContactoChanging(string value);
    partial void OnContactoChanged();
    #endregion
		
		public Usuario()
		{
			this._Notificacions = new EntitySet<Notificacion>(new Action<Notificacion>(this.attach_Notificacions), new Action<Notificacion>(this.detach_Notificacions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoUsuario", DbType="Int NOT NULL")]
		public int IdTipoUsuario
		{
			get
			{
				return this._IdTipoUsuario;
			}
			set
			{
				if ((this._IdTipoUsuario != value))
				{
					this.OnIdTipoUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdTipoUsuario = value;
					this.SendPropertyChanged("IdTipoUsuario");
					this.OnIdTipoUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidoPaterno", DbType="NVarChar(225) NOT NULL", CanBeNull=false)]
		public string ApellidoPaterno
		{
			get
			{
				return this._ApellidoPaterno;
			}
			set
			{
				if ((this._ApellidoPaterno != value))
				{
					this.OnApellidoPaternoChanging(value);
					this.SendPropertyChanging();
					this._ApellidoPaterno = value;
					this.SendPropertyChanged("ApellidoPaterno");
					this.OnApellidoPaternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contacto", DbType="NVarChar(255)")]
		public string Contacto
		{
			get
			{
				return this._Contacto;
			}
			set
			{
				if ((this._Contacto != value))
				{
					this.OnContactoChanging(value);
					this.SendPropertyChanging();
					this._Contacto = value;
					this.SendPropertyChanged("Contacto");
					this.OnContactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Notificacion", Storage="_Notificacions", ThisKey="IdUsuario", OtherKey="IdUsuario")]
		public EntitySet<Notificacion> Notificacions
		{
			get
			{
				return this._Notificacions;
			}
			set
			{
				this._Notificacions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Notificacions(Notificacion entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Notificacions(Notificacion entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Correo")]
	public partial class Correo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCorreo;
		
		private string _Remitente;
		
		private string _Destinatario;
		
		private string _CC;
		
		private string _BCC;
		
		private string _Asunto;
		
		private string _CuerpoTexto;
		
		private string _CuerpoHTML;
		
		private System.DateTime _FechaCreacion;
		
		private System.Nullable<System.DateTime> _FechaProgramadaEnvio;
		
		private System.Nullable<System.DateTime> _FechaEnvio;
		
		private System.Nullable<int> _IntentoFallido;
		
		private bool _Pendiente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCorreoChanging(int value);
    partial void OnIdCorreoChanged();
    partial void OnRemitenteChanging(string value);
    partial void OnRemitenteChanged();
    partial void OnDestinatarioChanging(string value);
    partial void OnDestinatarioChanged();
    partial void OnCCChanging(string value);
    partial void OnCCChanged();
    partial void OnBCCChanging(string value);
    partial void OnBCCChanged();
    partial void OnAsuntoChanging(string value);
    partial void OnAsuntoChanged();
    partial void OnCuerpoTextoChanging(string value);
    partial void OnCuerpoTextoChanged();
    partial void OnCuerpoHTMLChanging(string value);
    partial void OnCuerpoHTMLChanged();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    partial void OnFechaProgramadaEnvioChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaProgramadaEnvioChanged();
    partial void OnFechaEnvioChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaEnvioChanged();
    partial void OnIntentoFallidoChanging(System.Nullable<int> value);
    partial void OnIntentoFallidoChanged();
    partial void OnPendienteChanging(bool value);
    partial void OnPendienteChanged();
    #endregion
		
		public Correo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCorreo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdCorreo
		{
			get
			{
				return this._IdCorreo;
			}
			set
			{
				if ((this._IdCorreo != value))
				{
					this.OnIdCorreoChanging(value);
					this.SendPropertyChanging();
					this._IdCorreo = value;
					this.SendPropertyChanged("IdCorreo");
					this.OnIdCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remitente", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Remitente
		{
			get
			{
				return this._Remitente;
			}
			set
			{
				if ((this._Remitente != value))
				{
					this.OnRemitenteChanging(value);
					this.SendPropertyChanging();
					this._Remitente = value;
					this.SendPropertyChanged("Remitente");
					this.OnRemitenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Destinatario", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Destinatario
		{
			get
			{
				return this._Destinatario;
			}
			set
			{
				if ((this._Destinatario != value))
				{
					this.OnDestinatarioChanging(value);
					this.SendPropertyChanging();
					this._Destinatario = value;
					this.SendPropertyChanged("Destinatario");
					this.OnDestinatarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC", DbType="NVarChar(255)")]
		public string CC
		{
			get
			{
				return this._CC;
			}
			set
			{
				if ((this._CC != value))
				{
					this.OnCCChanging(value);
					this.SendPropertyChanging();
					this._CC = value;
					this.SendPropertyChanged("CC");
					this.OnCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BCC", DbType="NVarChar(255)")]
		public string BCC
		{
			get
			{
				return this._BCC;
			}
			set
			{
				if ((this._BCC != value))
				{
					this.OnBCCChanging(value);
					this.SendPropertyChanging();
					this._BCC = value;
					this.SendPropertyChanged("BCC");
					this.OnBCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asunto", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Asunto
		{
			get
			{
				return this._Asunto;
			}
			set
			{
				if ((this._Asunto != value))
				{
					this.OnAsuntoChanging(value);
					this.SendPropertyChanging();
					this._Asunto = value;
					this.SendPropertyChanged("Asunto");
					this.OnAsuntoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuerpoTexto", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string CuerpoTexto
		{
			get
			{
				return this._CuerpoTexto;
			}
			set
			{
				if ((this._CuerpoTexto != value))
				{
					this.OnCuerpoTextoChanging(value);
					this.SendPropertyChanging();
					this._CuerpoTexto = value;
					this.SendPropertyChanged("CuerpoTexto");
					this.OnCuerpoTextoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuerpoHTML", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string CuerpoHTML
		{
			get
			{
				return this._CuerpoHTML;
			}
			set
			{
				if ((this._CuerpoHTML != value))
				{
					this.OnCuerpoHTMLChanging(value);
					this.SendPropertyChanging();
					this._CuerpoHTML = value;
					this.SendPropertyChanged("CuerpoHTML");
					this.OnCuerpoHTMLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaProgramadaEnvio", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaProgramadaEnvio
		{
			get
			{
				return this._FechaProgramadaEnvio;
			}
			set
			{
				if ((this._FechaProgramadaEnvio != value))
				{
					this.OnFechaProgramadaEnvioChanging(value);
					this.SendPropertyChanging();
					this._FechaProgramadaEnvio = value;
					this.SendPropertyChanged("FechaProgramadaEnvio");
					this.OnFechaProgramadaEnvioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEnvio", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaEnvio
		{
			get
			{
				return this._FechaEnvio;
			}
			set
			{
				if ((this._FechaEnvio != value))
				{
					this.OnFechaEnvioChanging(value);
					this.SendPropertyChanging();
					this._FechaEnvio = value;
					this.SendPropertyChanged("FechaEnvio");
					this.OnFechaEnvioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntentoFallido", DbType="Int")]
		public System.Nullable<int> IntentoFallido
		{
			get
			{
				return this._IntentoFallido;
			}
			set
			{
				if ((this._IntentoFallido != value))
				{
					this.OnIntentoFallidoChanging(value);
					this.SendPropertyChanging();
					this._IntentoFallido = value;
					this.SendPropertyChanged("IntentoFallido");
					this.OnIntentoFallidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pendiente", DbType="Bit NOT NULL")]
		public bool Pendiente
		{
			get
			{
				return this._Pendiente;
			}
			set
			{
				if ((this._Pendiente != value))
				{
					this.OnPendienteChanging(value);
					this.SendPropertyChanging();
					this._Pendiente = value;
					this.SendPropertyChanged("Pendiente");
					this.OnPendienteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
